name: obsidian2hexo-deploy-actions
# 把 obsidian 转换成博客
on:
  push:
    branches:
      # 监听 master 分支如果有变动调用当前Actions
      - master
  repository_dispatch:
      types:
        - hexo-template-update
# 环境变量
env:
  HEXO_TEMPLATE: 7zMonkey/obsidian2hexo-template
  BLOG: 7zMonkey/7zMonkey.github.io
jobs:
# 拉取 hexo 模板
  obsidian2hexo-deploy-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ env.HEXO_TEMPLATE }}
          path: hexo-template

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: obsidian-doc
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Mv docs
        run: |
          mkdir -p hexo-template/source/_posts
          mv obsidian-doc/博客/* hexo-template/source/_posts
      - name: Hexo generate
        run: |
          cd hexo-template
          npm install
          npm install -g hexo-cli
          hexo generate
        
      # - name: Checkout code
      #   uses: actions/checkout@v2
      #   with:
      #     repository: 7zMonkey/7zMonkey.github.io
      #     path: blog
      #     fetch-depth: 0
        # run 后面跟随 git 拉取的仓库 目标路径改为blog

      - name: Move Generate Files
        run: |
          mkdir blog
          mv hexo-template/public/* blog
      
      - name: Ls
        run: ls -a blog

      # - name: 部署到 GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./blog

      # - name: Call other repository workflow
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #     token: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      #     repository: ${{ env.BLOG }}
      #     event-type: devops-hexo
      
      # - name: 部署页面
      #   uses: JamesIves/github-pages-deploy-action@v4.2.5
      #   with:
      #     branch: master
      #     folder: blog
      #     repository-name: 7zMonkey/test-actions
      #     clean: false
      #     # clean-exclude: .nojekyll
      #     #   .ssh
      #     #   .git
      #     ssh-key: ${{ secrets.DEPLOY_KEY }}
      #     # token: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Push To Pages
        working-directory: ./blog # 指定下面指令运行的目录
        run: |
          git init
          git checkout -b main
          git add -A
          git -c user.name='${{ secrets.NAME }}' -c user.email='${{ secrets.EMAIL }}' commit -m 'deploy by actions <${{secrets.NAME}}>'
          git remote add origin https://${{secrets.SERVICE_ACCOUNT_KEY}}@github.com/${{env.BLOG}}.git
          git push origin main -f -q
